### ISSUE TITLE
Content Source Loading Failed on open

### ISSUE THREAD

**Issue by GaussLM** [justastranger/CarcassSpark#19]
Throws an exception and does not finish loading [vanilla] game files.  I can load my mod just fine though if I ignore the exception and select File>Open Mod.

Occurs on both a Steam and a fresh GOG install (details from the latter below).

64-bit Windows 10, if that matters.  Haven't touched it in a few weeks at least, and was in the process of migrating some stuff from Steam to GOG when I encountered this, though I doubt that's related.  I downloaded a fresh copy of Carcass Spark to verify that wasn't the issue, no difference.

![image](https://github.com/justastranger/CarcassSpark/assets/66341456/dd5cd489-ba01-4718-8a8b-91d401b67d89)

<details>
<summary>Exception Text etc</summary>
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Loading Failed
   at CarcassSpark.ObjectViewers.ModViewerTabControl..ctor(String location, Boolean isVanilla, Boolean newMod)
   at CarcassSpark.ObjectViewers.TabbedModViewer.CreateNewModViewerTab(String folder, Boolean isVanilla, Boolean newMod)
   at CarcassSpark.ObjectViewers.TabbedModViewer.InitializeTabs()
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Carcass Spark
    Assembly Version: 0.15.2.0
    Win32 Version: 0.15.2
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/Carcass%20Spark.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4629.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
AssetStudio
    Assembly Version: 0.16.0.0
    Win32 Version: 0.16.0
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/AssetStudio.DLL
----------------------------------------
AssetStudioUtility
    Assembly Version: 0.16.0.0
    Win32 Version: 0.16.0
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/AssetStudioUtility.DLL
----------------------------------------
SixLabors.ImageSharp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.3.0
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/SixLabors.ImageSharp.DLL
----------------------------------------
SixLabors.ImageSharp.Drawing
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/SixLabors.ImageSharp.Drawing.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/System.Memory.DLL
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/System.Buffers.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Texture2DDecoderWrapper
    Assembly Version: 0.15.24.0
    Win32 Version: 0.15.24
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/Texture2DDecoderWrapper.DLL
----------------------------------------
SixLabors.Fonts
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/SixLabors.Fonts.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
AssetStudio.PInvoke
    Assembly Version: 0.16.0.0
    Win32 Version: 0.16.0
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/AssetStudio.PInvoke.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///E:/GOG%20Galaxy/Games/Cultist%20Simulator/Carcass.Spark.0.15.2/System.Numerics.Vectors.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
</details>

**Comment by justastranger** [comment]
Carcass Spark is unfortunately not updated for the latest versions of the
game and is likely not going to be. Sorry for the inconvenience.
